services:
  db:
    container_name: boilerplate_db
    profiles: ['dev', 'db']
    image: postgres
    restart: 'no'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 1s
      timeout: 5s
      retries: 10
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
